<h2>SEO</h2>

<div data-ng-cloak>
    <div data-ng-controller="optionsForm" data-ng-init="namespace = 'Chayka.SEO'">
        <form data-form-validator="validator" novalidate="novalidate">
            <div class="form_field fullsize custom_sitemap_paths" data-form-field="customSitemapPaths">
                <label class="">Custom Sitemap Paths</label><textarea data-ng-init="options.customSitemapPaths=''" data-ng-model="options.customSitemapPaths" title="Custom Sitemap Paths"></textarea>
            </div>
            <div class="note" data-ng-init="sitemapPackOptions = {'none':'No','yearly':'Yearly','monthly':'Monthly'}" ></div>
            <?php $postTypes = get_post_types(['public'=>true]); unset($postTypes['attachment']);?>
            <div class="form_field stretch max_entry_pack_size" data-form-field="maxEntryPackSize">
                <label class="width70">Max Entry Pack Size</label><input type="text" data-ng-init="options.maxEntryPackSize='10'" data-ng-model="options.maxEntryPackSize" title="Max Entry Pack Size"/>
            </div>
            <label>Sitemap Post Types:</label>
            <div class="form_field checkboxes sitemap_need_type">
                <?php foreach($postTypes as $postType):?>
                <label>
                    <input type="checkbox" data-ng-init="options.sitemap_need_type_<?php echo $postType?>='1'" data-ng-model="options.sitemap_need_type_<?php echo $postType?>" data-ng-true-value="'1'" data-ng-false-value="'0'" title="<?php echo $postType?>"/>
                    <?php echo $postType?>
                </label>
                <?php endforeach;?>
            </div>


	        <!-- chayka: fields -->
            <div class="buttons">
                <button class="button button-primary button-large" data-ng-click="saveOptions();">Save</button>
            </div>
        </form>
    </div>
</div>